apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jubileeverse

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "8.0.0"

images:
  - name: jubileeverse/app
    newTag: latest
